extends:
  - 'standard-with-typescript'
  - 'plugin:jsdoc/recommended'

parserOptions:
  project: './tsconfig.json'

rules:
  'jsdoc/require-param-type': off
  'jsdoc/require-returns-type': off
  'jsdoc/no-types': error
